[package]
name = "s3-bang"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.55.1"
aws-sdk-s3 = "0.26.0"
inquire = "0.6.1"
tokio = { version = "1", features = ["full"] }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

